<a href="https://colab.research.google.com/github/kunal-geeks/kunal-geeks/blob/main/python_assignment_kunal_sharma.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1- Write python scripts which takes the given input and return the following output-

      Input: “abcd”
      Output: “_A_B_C_D”


In [17]:
str = "abcd"
new_str = []
for x in str:
  new_str.append('_')
  new_str.append(x.upper())
s = ""
print(s.join(new_str))

_A_B_C_D


2- Write Python script to find the sum of all items in a dictionary

    Input: {‘a’: 100, ‘b’:200, ‘c’:300}
    Output: 600


In [40]:
dict_a = {'a' : 100,'b' : 200,'c' : 300}
sum = 0
for x in dict_a.values():
  sum += x
print(sum)

600


3- Python script to remove duplicates from list-
 [1,2,3,4,5,4,6,4,6,7,4,8,9]


In [42]:
list1 =  [1,2,3,4,5,4,6,4,6,7,4,8,9]
a = set(list1)
print(list(a))

[1, 2, 3, 4, 5, 6, 7, 8, 9]


4- Sort the given list of tuples using Lambda function

Marks=[('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]


In [63]:
Marks=[('English', 88), ('Science', 90), ('Maths', 97), ('Social sciences', 82)]
Marks.sort(key = lambda x : x[1])
print(Marks)


[('Social sciences', 82), ('English', 88), ('Science', 90), ('Maths', 97)]


5- Write a Python Script to swap the first and last element of the given list-

Input: [12, 35, 9, 56, 24]

Output: [24, 35, 9, 56, 12]


In [64]:
a = [12, 35, 9, 56, 24]
temp = a[0]
a[0] = a[len(a) - 1]
a[len(a) - 1] = temp
print(a)

[24, 35, 9, 56, 12]


6- Write a Python Script to print even length words in a string-

Input: s = "I am Shailja"

Output: am


In [1]:
s = "I am Shailja"
a = []
b = ""
for i in s:
  if(i == " "):
    a.append(b)
    b = ""
    continue
  else:
    b += i
a.append(b)    
for i in range(len(a)):
  if(i % 2 != 0):
    print(a[i],end = " ")

am 

**NUMPY**


1- Create a numpy array for the below data and find the number of occurrences of a [9,4] sequence 

Raw_data= [[2, 8, 9, 4],[9, 4, 9, 4],[4, 5, 9, 7],[2, 9, 4, 3]])


In [40]:
import numpy as np
Raw_data= [[2, 8, 9, 4],[9, 4, 9, 4],[4, 5, 9, 7],[2, 9, 4, 3]]
arr = np.array(Raw_data)
#output = repr(arr).count("9, 4")
#print(output)
count = 0
for i in range(4):
  for j in range(3):
    if(arr[i][j] == 9 and arr[i][j+1] == 4):
       count += 1
print(count)

4


2- Create a numpy array for the below data :
Raw_data = [1,2,3,4,5,1,2,1,1,1]

a: find the most frequent value in the array

b: Find the data type and change it to float


In [2]:
import numpy as np
Raw_data = [1,2,3,4,5,1,2,1,1,1]
arr = np.array(Raw_data)
count = {}
for i in range(arr.size):
  if(arr[i] in  count.keys()):
   count[arr[i]] += 1
  else:
   count[arr[i]] = 1
most_freq_value = count[max(count.values())]
print(most_freq_value)
arr = arr.astype('float64')
print(arr.dtype)
print(arr)

1
float64
[1. 2. 3. 4. 5. 1. 2. 1. 1. 1.]


3-  Flatten a 2d numpy array into 1d array

 E.g- initial array
                     [[1 2 3]
                     [2 4 5]
                     [1 2 3]]

New resulting array: [1 2 3 2 4 5 1 2 3]


In [11]:
import numpy as np
arr = np.array([[1,2,3],[2,4,5],[1,2,3]])
a = []
for i in range(3):
  for j in range(3):
    a.append(arr[i][j])
print(a)


[1, 2, 3, 2, 4, 5, 1, 2, 3]


**PANDAS:**

1- Create a Pandas Data frame from the given data and create a new column “Voter” based on voter age, i.e., if age >18 then voter column should be “Yes” otherwise if age <18 then voter column should be “No”

raw_Data = 
{
  
           'Voter_name': ['Geek1', 'Geek2', 'Geek3', 'Geek4', 'Geek5', 'Geek6', 'Geek7', 'Geek8'], 

            'Voter_age': [15, 23, 25, 9, 67, 54, 42, np.NaN]}


In [25]:
import pandas as pd
import numpy as np
raw_data ={ 'Voter_name': ['Geek1', 'Geek2', 'Geek3', 'Geek4', 'Geek5', 'Geek6', 'Geek7', 'Geek8'], 

             'Voter_age': [15, 23, 25, 9, 67, 54, 42, np.NaN]}
df = pd.DataFrame(raw_data)
Voter = []
for i in list(df['Voter_age']):
  if(i > 18):
    Voter.append('Yes')
  else:
    Voter.append('No')
df['Voter']  = Voter
display(df)

Voter_name  Voter_age Voter
0      Geek1       15.0    No
1      Geek2       23.0   Yes
2      Geek3       25.0   Yes
3      Geek4        9.0    No
4      Geek5       67.0   Yes
5      Geek6       54.0   Yes
6      Geek7       42.0   Yes
7      Geek8        NaN    No

2 – Create a Pandas Data frame from the given data and collapse First and Last column into one column as Full Name, so the output contains Full Name and Age, then convert column age to index
raw_Data = 
{
    
     'First': ['Manan ', 'Raghav ', 'Sunny '],
      'Last': ['Goel', 'Sharma', 'Chawla'],
      'Age' : [12, 24, 56]}


In [40]:
import pandas as pd
raw_data = { 'First': ['Manan ', 'Raghav ', 'Sunny '],
              'Last': ['Goel', 'Sharma', 'Chawla'],
              'Age' : [12, 24, 56]}
df = pd.DataFrame(raw_data)
df['Full Name'] = df['First'] + df['Last']
del df['First'],df['Last']
df = df.set_index('Age')
print(df)

         Full Name
Age               
12      Manan Goel
24   Raghav Sharma
56    Sunny Chawla


3- Create a Pandas Data frame from the given data -
raw_Data = {
              
              'Date':['10/2/2011', '11/2/2011', '12/2/2011', '13/2/2011'],
           'Product':['Umbrella', 'Matress', 'Badminton','Shuttle'],
             'Price':[1250, 1450, 1550, 400],
           'Expense': [ 21525220.653, 31125840.875, 23135428.768, 56245263.942]}

a- Add Index as Item1, Item2, Item3, Item4 

b- Find the index labels of all items whose ‘Price’ is greater than 1000.

c- Replace products using Map() with respective codes- Umbrella : ‘U’, Matress : 'M', Badminton : 'B', Shuttle: 'S'

d- Round off the Expense column values to two decimal places.

e- Create a new column called ‘Discounted_Price’ after applying a 10% discount on the existing ‘price’ column.(try using lambda function)

f- Convert the column type of “Date” to datetime format 

g- Create a column rank which ranks the products based on the price (one with highest price will be rank 1).


In [73]:
import pandas as pd
df = pd.DataFrame({ 'Date':['10/2/2011', '11/2/2011', '12/2/2011', '13/2/2011'],
                 'Product':['Umbrella', 'Matress', 'Badminton','Shuttle'],
                   'Price':[1250, 1450, 1550, 400],
                 'Expense': [21525220.653, 31125840.875, 23135428.768, 56245263.942]})
df.columns.values[0] = "item1"
df.columns.values[1] = "item2"
df.columns.values[2] = "item3"
df.columns.values[3] = "item4"
#print(df)
# b)
df1 =df[df['item3'] > 1000] 
print(df1)
# c)
df['item2'] = df['item2'].map({'Umbrella':'U',
                             'Matress':'M',
                             'Badminton':'B',
                             'Shuttle':'S'},
                             na_action=None)
#print(df)
# d)
df['item4'] = df['item4'].round(decimals = 2)
print(df)
# e)
df['Discounted_Price'] = list(map(lambda x : x * 0.9,df['item3'].values))
print(df)
# f)
df['item1']= pd.to_datetime(df['item1'])
print(df)
# g)
df["Rank"] = df["item3"].rank(ascending = False)
df.sort_values("Rank", inplace = True,)
print(df)

       item1      item2  item3         item4
0  10/2/2011   Umbrella   1250  2.152522e+07
1  11/2/2011    Matress   1450  3.112584e+07
2  12/2/2011  Badminton   1550  2.313543e+07
       item1 item2  item3        item4
0  10/2/2011     U   1250  21525220.65
1  11/2/2011     M   1450  31125840.88
2  12/2/2011     B   1550  23135428.77
3  13/2/2011     S    400  56245263.94
       item1 item2  item3        item4  Discounted_Price
0  10/2/2011     U   1250  21525220.65            1125.0
1  11/2/2011     M   1450  31125840.88            1305.0
2  12/2/2011     B   1550  23135428.77            1395.0
3  13/2/2011     S    400  56245263.94             360.0
       item1 item2  item3        item4  Discounted_Price
0 2011-10-02     U   1250  21525220.65            1125.0
1 2011-11-02     M   1450  31125840.88            1305.0
2 2011-12-02     B   1550  23135428.77            1395.0
3 2011-02-13     S    400  56245263.94             360.0
       item1 item2  item3        item4  Discounted_Pric

4 -  Read the csv provide(nba.csv) into a dataframe-

a: Remove nulls(if any)and get details of people with top 5 Age

b: Get the index at which minimum weight value is present.

c: Sort values based on name in alphabetical order for the rows (the original dataframe sorting should not change)

d: Create a series from given dataframe on “name” column and display top and last 10

e: Display: 
*Number of rows and columns in dataframe

*Index, Datatype in dataframe

*Summary statistics for numerical columns
 
*Unique values and counts for all columns


In [99]:
import pandas as pd

data = pd.read_csv('nba.csv')
display(data)

Name            Team  Number Position  Age  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25     180   
1      Jae Crowder  Boston Celtics      99       SF   25     235   
2     John Holland  Boston Celtics      30       SG   27     205   
3      R.J. Hunter  Boston Celtics      28       SG   22     185   
4    Jonas Jerebko  Boston Celtics       8       PF   29     231   
..             ...             ...     ...      ...  ...     ...   
452     Trey Lyles       Utah Jazz      41       PF   20     234   
453   Shelvin Mack       Utah Jazz       8       PG   26     203   
454      Raul Neto       Utah Jazz      25       PG   24     179   
455   Tibor Pleiss       Utah Jazz      21        C   26     256   
456    Jeff Withey       Utah Jazz      24        C   26     231   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3        Georgia State  1148640.0  
4                  NaN  5000000.0  
..                 ...        ...  
452           Kentucky  2239800.0  
453             Butler  2433333.0  
454                NaN   900000.0  
455                NaN  2900000.0  
456             Kansas   947276.0  

[457 rows x 8 columns]

In [6]:
import pandas as pd

data = pd.read_csv('/root/kunal/nba.csv')

#print(data.isnull().sum())
#a)
data = data.fillna(' ')
display(data.head())
#b)
print(data[['Weight']].idxmin())
#c)
sorted_df = data.sort_values(by = 'Name')
display(sorted_df)
#d)
df = pd.Series(list(data['Name']))
display(df.head(10))
display(df.tail(10))
# e)
print(data.shape)
display(data.info())
display(data.describe())
data.agg(['count', 'size', 'nunique'])

Name            Team  Number Position  Age  Weight  \
0  Avery Bradley  Boston Celtics       0       PG   25     180   
1    Jae Crowder  Boston Celtics      99       SF   25     235   
2   John Holland  Boston Celtics      30       SG   27     205   
3    R.J. Hunter  Boston Celtics      28       SG   22     185   
4  Jonas Jerebko  Boston Celtics       8       PF   29     231   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University             
3      Georgia State  1148640.0  
4                     5000000.0

Weight    152
dtype: int64


Name                    Team  Number Position  Age  Weight  \
152     Aaron Brooks           Chicago Bulls       0       PG   31     161   
356     Aaron Gordon           Orlando Magic       0       PF   20     220   
328   Aaron Harrison       Charlotte Hornets       9       SG   21     210   
404    Adreian Payne  Minnesota Timberwolves      33       PF   25     237   
312       Al Horford           Atlanta Hawks      15        C   30     245   
..               ...                     ...     ...      ...  ...     ...   
386  Wilson Chandler          Denver Nuggets      21       SF   29     225   
270   Xavier Munford       Memphis Grizzlies      14       PG   24     180   
402      Zach LaVine  Minnesota Timberwolves       8       PG   21     189   
271    Zach Randolph       Memphis Grizzlies      50       PF   34     260   
237    Zaza Pachulia        Dallas Mavericks      27        C   32     275   

            College      Salary  
152          Oregon   2250000.0  
356         Arizona   4171680.0  
328        Kentucky    525093.0  
404  Michigan State   1938840.0  
312         Florida  12000000.0  
..              ...         ...  
386          DePaul  10449438.0  
270    Rhode Island              
402            UCLA   2148360.0  
271  Michigan State   9638555.0  
237                   5200000.0  

[457 rows x 8 columns]

0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
5     Amir Johnson
6    Jordan Mickey
7     Kelly Olynyk
8     Terry Rozier
9     Marcus Smart
dtype: object

447       Rudy Gobert
448    Gordon Hayward
449       Rodney Hood
450        Joe Ingles
451     Chris Johnson
452        Trey Lyles
453      Shelvin Mack
454         Raul Neto
455      Tibor Pleiss
456       Jeff Withey
dtype: object

(457, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    int64 
 3   Position  457 non-null    object
 4   Age       457 non-null    int64 
 5   Weight    457 non-null    int64 
 6   College   457 non-null    object
 7   Salary    457 non-null    object
dtypes: int64(3), object(5)
memory usage: 28.7+ KB


None

Number         Age      Weight
count  457.000000  457.000000  457.000000
mean    17.678337   26.938731  221.522976
std     15.966090    4.404016   26.368343
min      0.000000   19.000000  161.000000
25%      5.000000   24.000000  200.000000
50%     13.000000   26.000000  220.000000
75%     25.000000   30.000000  240.000000
max     99.000000   40.000000  307.000000

Name  Team  Number  Position  Age  Weight  College  Salary
count     457   457     457       457  457     457      457     457
size      457   457     457       457  457     457      457     457
nunique   457    30      53         5   22      87      119     310